"""Build dist/gridtools - a standalone plugin with only the sheet grid tools.

    QT_QPA_PLATFORM=offscreen python3 tools/build_gridtools.py

The sheet tools share maths (core/gridmath.py, core/paper.py) and QGIS helpers
(algs/_grid.py), so they cannot be single-file drop-in scripts. This flattens
them into one self-contained plugin folder that can be copied anywhere, with
its own provider id so it coexists with the full Field Kit plugin.

Generated, not hand-maintained: re-run this after changing any sheet tool.
"""

import os
import re
import shutil
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "dist", "gridtools")

# source -> destination filename
COPY = {
    "fieldkit/core/gridmath.py": "gridmath.py",
    "fieldkit/core/paper.py": "paper.py",
    "fieldkit/algs/_grid.py": "gridhelp.py",
    "fieldkit/algs/atlas_grid_builder.py": "atlas_grid_builder.py",
    "fieldkit/algs/sheet_estimator.py": "sheet_estimator.py",
    "fieldkit/algs/renumber_sheets.py": "renumber_sheets.py",
}

# The package is flat, so the two-level relative imports have to come down a level.
REWRITES = [
    (r"^from \.\.core import gridmath, paper$", "from . import gridmath, paper"),
    (r"^from \.\.core import gridmath$", "from . import gridmath"),
    (r"^from \.\.core import paper$", "from . import paper"),
    (r"^from \. import _grid$", "from . import gridhelp as _grid"),
]

BANNER = '''"""Generated by tools/build_gridtools.py from the Field Kit sources.

Edit fieldkit/ in the repository and re-run the builder rather than editing
this copy, or the two will drift apart.
"""
'''

METADATA = """[general]
name=Grid Tools
qgisMinimumVersion=3.34
description=Atlas sheet grids sized from paper and scale, sheet count estimates, and renumbering after you move sheets by hand.
version=0.2.0
author=Joeywoody124
email=joeywoody124@gmail.com

about=The sheet layout half of Field Kit, packaged on its own. Builds a numbered atlas sheet grid from a coverage polygon, a paper size and an engineering scale; estimates how many sheets a site takes across a ladder of scales without creating anything; and rebuilds sheet numbering, grid references and neighbour links from position after you have moved sheets around by hand. Installs alongside the full Field Kit plugin without clashing.

tracker=https://github.com/Joeywoody124/Bulk_Vector_Clip/issues
repository=https://github.com/Joeywoody124/Bulk_Vector_Clip
homepage=https://github.com/Joeywoody124/Bulk_Vector_Clip

tags=processing,atlas,layout,grid,sheets,civil

category=Plugins
experimental=True
deprecated=False
hasProcessingProvider=yes
"""

INIT = '''"""Grid Tools - atlas sheet grids for QGIS."""


def classFactory(iface):  # noqa: N802 - the name QGIS looks for
    from .plugin import GridToolsPlugin

    return GridToolsPlugin(iface)
'''

PLUGIN = '''"""Plugin entry point: register the Processing provider, and take it away again."""

from qgis.core import QgsApplication

from .provider import GridToolsProvider


class GridToolsPlugin:
    def __init__(self, iface):
        self.iface = iface
        self.provider = None

    def initGui(self):
        # Hold the reference: the registry does not own the Python object, and
        # a garbage-collected provider registers nothing and reports no error.
        self.provider = GridToolsProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def unload(self):
        if self.provider is not None:
            QgsApplication.processingRegistry().removeProvider(self.provider)
            self.provider = None
'''

PROVIDER = '''"""The Processing provider that puts the grid tools in the toolbox."""

from qgis.core import QgsProcessingProvider

from .atlas_grid_builder import AtlasGridBuilder
from .renumber_sheets import RenumberSheets
from .sheet_estimator import SheetEstimator

ALGORITHMS = [AtlasGridBuilder, SheetEstimator, RenumberSheets]


class GridToolsProvider(QgsProcessingProvider):
    def loadAlgorithms(self):
        for algorithm in ALGORITHMS:
            self.addAlgorithm(algorithm())

    def id(self):
        # Deliberately not "fieldkit", so this can sit alongside the full
        # plugin without the two fighting over algorithm ids.
        return "gridtools"

    def name(self):
        return "Grid Tools"

    def longName(self):
        return "Grid Tools - atlas sheet grids, estimates and renumbering"

    def supportsNonFileBasedOutput(self):
        return True
'''

INSTALL_BAT = r"""@echo off
REM Link this folder into the QGIS plugins directory.
REM A junction (/J) does not need administrator rights, and edits to the code
REM here show up in QGIS after a plugin reload.

setlocal
set "SRC=%~dp0"
if %SRC:~-1%==\ set "SRC=%SRC:~0,-1%"
set "DEST=%APPDATA%\QGIS\QGIS3\profiles\default\python\plugins\gridtools"

if exist "%DEST%" (
    echo Something is already at:
    echo   %DEST%
    echo Remove it first ^(rmdir "%DEST%"^) then run this again.
    pause
    exit /b 1
)

if not exist "%APPDATA%\QGIS\QGIS3\profiles\default\python\plugins" (
    echo Could not find the QGIS plugins folder at:
    echo   %APPDATA%\QGIS\QGIS3\profiles\default\python\plugins
    echo Start QGIS once to create it, or check you are using the "default" profile.
    pause
    exit /b 1
)

mklink /J "%DEST%" "%SRC%"
if errorlevel 1 (
    echo.
    echo Junction failed. Copy the folder instead:
    echo   xcopy /E /I "%SRC%" "%DEST%"
    pause
    exit /b 1
)

echo.
echo Linked. Now start QGIS and enable "Grid Tools" in
echo   Plugins  -^>  Manage and Install Plugins  -^>  Installed
echo Tick "Show also experimental plugins" in Settings if it is not listed.
pause
"""


def build():
    if os.path.isdir(OUT):
        shutil.rmtree(OUT)
    os.makedirs(OUT)

    for source, destination in COPY.items():  # noqa: PLR1702
        with open(os.path.join(ROOT, source), encoding="utf-8") as handle:
            text = handle.read()

        lines = text.split("\n")
        for index, line in enumerate(lines):
            for pattern, replacement in REWRITES:
                if re.match(pattern, line):
                    lines[index] = replacement
                    break
        text = "\n".join(lines)

        if "from . import" not in text and "import" in text:
            pass  # pure module, nothing to rewrite

        with open(os.path.join(OUT, destination), "w", encoding="utf-8") as handle:
            handle.write(BANNER + "\n" + text)
        print("  %-34s -> %s" % (source, destination))

    for name, content in (
        ("__init__.py", INIT),
        ("plugin.py", PLUGIN),
        ("provider.py", PROVIDER),
        ("metadata.txt", METADATA),
        ("install_windows.bat", INSTALL_BAT),
    ):
        with open(os.path.join(OUT, name), "w", encoding="utf-8",
                  newline="\r\n" if name.endswith(".bat") else None) as handle:
            handle.write(content)
        print("  %-34s -> %s" % ("(generated)", name))

    readme = os.path.join(ROOT, "tools", "gridtools_README.md")
    shutil.copy(readme, os.path.join(OUT, "README.md"))
    print("  %-34s -> %s" % ("tools/gridtools_README.md", "README.md"))

    sample = os.path.join(ROOT, "sample", "fieldkit_demo.gpkg")
    if os.path.exists(sample):
        shutil.copy(sample, os.path.join(OUT, "sample_sites.gpkg"))
        print("  %-34s -> %s" % ("sample/fieldkit_demo.gpkg", "sample_sites.gpkg"))

    # No relative import may reach outside the flat package.
    problems = []
    for name in sorted(os.listdir(OUT)):
        if not name.endswith(".py"):
            continue
        with open(os.path.join(OUT, name), encoding="utf-8") as handle:
            for number, line in enumerate(handle, start=1):
                if line.startswith("from ..") or line.startswith("import .."):
                    problems.append("%s:%d %s" % (name, number, line.strip()))
    if problems:
        raise SystemExit("Unrewritten parent imports:\n  " + "\n  ".join(problems))

    print("\nBuilt %s" % OUT)


if __name__ == "__main__":
    build()
    sys.exit(0)
